development:
  adapter: postgresql
  encoding: unicode
  database: development_softline
  pool: 5
  username: charles
  password: gesthos4620

test:
  adapter: postgresql
  encoding: unicode
  database: test_softline
  pool: 5
  username: charles
  password: gesthos4620

production:
  adapter: postgresql
  encoding: unicode
  database: production_softline
  pool: 5
  username: charles
  password: gesthos4620